version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - ./.env # Path to the .env file in the root directory
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/etl_db
    ports:
      - "5000:5000"

  db:
    build: ./database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
